server: 
  port: 8081
  servlet: 
    context-path: /lsso-resource-server

####### resource server configuration properties
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://
  jpa:
    defer-datasource-initialization: true