server:
  port: 8081
  servlet:
    context-path: /lsso-resource-server

####### resource server configuration properties
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://
  datasource:
    username: sa
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE;
  jpa:
    defer-datasource-initialization: true
    open-in-view: false
  devtools:
    livereload:
      port: 35730
