spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: github-client-id
            client-secret: github-client-secret
  thymeleaf:
    cache: false
    
server: 
  port: 8082
  servlet: 
    context-path: /lsso-client
    
logging: 
  level: 
    org.springframework: INFO
        